**Q1. Lets consider your data is like the below cell:**

**Q1-1**: Write a program that create a dataframe from the data.

**Q1-2:** Select people that are psychologist or teacher and their number of cars is greater than their family size.

**Q1-3:** Select people who have at most 2 family members and at least 1 car.

**Q1-4:** Write a code that get number of unique jobs in this dataset.





In [ ]:
data = {"name": ["Joseph", "Jacob", "Sam", "Jesee", "Ryan", "Lisa", "Lee"],
        "job": ["teacher", "psychologist", "data scientist", "software developer", "psychologist", "psychologist", "teacher"],
        "family_size": [3, 2, 1, 4, 2, 3, 2],
        "num_cars": [3, 1, 1, 2, 2, 4, 1]}

In [ ]:
import pandas as pd
# Q1-1
data = {"name": ["Joseph", "Jacob", "Sam", "Jesee", "Ryan", "Lisa", "Lee"],
        "job": ["teacher", "psychologist", "data scientist", "software developer", "psychologist", "psychologist", "teacher"],
        "family_size": [3, 2, 1, 4, 2, 3, 2],
        "num_cars": [3, 1, 1, 2, 2, 4, 1]}

frame = pd.DataFrame(data, columns=["name","job","family_size","num_cars"])
print(frame,"\n")

# Q1-2
print(frame[((frame["job"] == "psychologist") | (frame["job"] == "teacher")) & (frame["num_cars"] > frame["family_size"])])


print("\n")

# Q1-3
print(frame[(frame["family_size"]<= 2) & (frame["num_cars"] >= 1)])

print("\n")

# Q1-4
unique = len(pd.unique(frame["job"]))
print("Number of unique jobs:",unique)

     name                 job  family_size  num_cars
0  Joseph             teacher            3         3
1   Jacob        psychologist            2         1
2     Sam      data scientist            1         1
3   Jesee  software developer            4         2
4    Ryan        psychologist            2         2
5    Lisa        psychologist            3         4
6     Lee             teacher            2         1 

   name           job  family_size  num_cars
5  Lisa  psychologist            3         4


    name             job  family_size  num_cars
1  Jacob    psychologist            2         1
2    Sam  data scientist            1         1
4   Ryan    psychologist            2         2
6    Lee         teacher            2         1


Number of unique jobs: 4


**Q2. Lets consider you have two series like the below cell. Compute the mean of weights of each fruit.**

In [ ]:
import numpy as np
fruit = pd.Series(np.random.choice(['apple', 'banana', 'carrot'], 10))
weights = pd.Series(np.linspace(1, 10, 10))

In [ ]:
import numpy as np
fruit = pd.Series(np.random.choice(['apple', 'banana', 'carrot'], 10))
weights = pd.Series(np.linspace(1, 10, 10))

print(fruit, "\n")
print(weights, "\n")
print("Mean of weights for each fruit:")
weights.groupby(fruit).mean()

0    banana
1    banana
2     apple
3    banana
4    carrot
5    carrot
6    banana
7    banana
8     apple
9    banana
dtype: object 

0     1.0
1     2.0
2     3.0
3     4.0
4     5.0
5     6.0
6     7.0
7     8.0
8     9.0
9    10.0
dtype: float64 

Mean of weights for each fruit:


apple     6.000000
banana    5.333333
carrot    5.500000
dtype: float64

**Q3. Consider the below course_name array:**

**Q3-1**: Write a NumPy program to get the indices of the sorted elements of **course_name** array.

**Q3-2:** Write numpy code to check whether each element of **course_name** array starts with "P".


In [ ]:
import numpy as np
course_name = np.array(['Python', 'JS', 'examples', 'PHP', 'html'])

In [ ]:
import numpy as np
course_name = np.array(['Python', 'JS', 'examples', 'PHP', 'html'])

#Q3-1
print("Course_name array:")
print(course_name, "\n")
indices = np.argsort(course_name)
print("Indices of the sorted elements of course_name array:")
print(indices,"\n")

#Q3-2
letter = "P"
check = np.char.startswith(course_name, letter, start = 0, end = None)
print("Checking whether each element starts with 'P':")
print(check)

Course_name array:
['Python' 'JS' 'examples' 'PHP' 'html'] 

Indices of the sorted elements of course_name array:
[1 3 0 2 4] 

Checking whether each element starts with 'P'
[ True False False  True False]


**Q4. Consider the below student_id array:**

**Q4-1:** Reverse the **student_id** array. Print both original and reversed array.

**Q4-2:** Get the 3-largest values of **student_id** array.

In [ ]:
import numpy as np
student_id = np.array([1023, 5202, 6230, 1671, 1682, 5241, 4532])

In [ ]:
import numpy as np
student_id = np.array([1023, 5202, 6230, 1671, 1682, 5241, 4532])

#Q4-1
reverse = np.flip(student_id)
print("Original:",student_id)
print("Reversed:",reverse)

#Q4-2
n = 3
print("3 largest values:", student_id[np.argsort(student_id)[-n:]])

Original: [1023 5202 6230 1671 1682 5241 4532]
Reversed: [4532 5241 1682 1671 6230 5202 1023]
3 largest values: [5202 5241 6230]


# **Q5: Write a numpy program to print sum of all the multiples of 3 or 5 below 100**

In [ ]:
import numpy as np
num = np.arange(1, 100)
multiples = num[(num % 3 == 0) | (num % 5 == 0)]
print("The sum of all the multiples of 3 or 5 below 100 is",multiples.sum())


The sum of all the multiples of 3 or 5 below 100 is 2318


**Q6. Consider the below array.**

Q6.1. Write a code to swap column 1 with column 2.

Q6.2. Write a code to swap row 0 with row 1.

In [ ]:
import numpy as np

arr = np.arange(12).reshape(3,4)
print(arr)

In [ ]:
import numpy as np

arr = np.arange(12).reshape(3,4)
print("Original:")
print(arr)
print("\n")

#Q6-1
arr[:,[0, 1]] = arr[:,[1, 0]]
print("Swapping column 1 with column 2:")
print(arr)
print("\n")

#Q6-2
arr[[0,1]] = arr[[1,0]]
print("Swapping row 0 with row 1:")
print(arr)

Original:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


Swapping column 1 with column 2:
[[ 1  0  2  3]
 [ 5  4  6  7]
 [ 9  8 10 11]]


Swapping row 0 with row 1:
[[ 5  4  6  7]
 [ 1  0  2  3]
 [ 9  8 10 11]]
